<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by MeroDoctor</title>
</head>
<body>
    <h1>Your password for login is: {{ $password }}</h1>
    <small style="color: red">Note: You can only login after your account has been approved by admin.</small>
    <p>Thank you</p>
</body>
</html> 